language: cpp
os: osx
compiler:
  - gcc
  - clang

addons:
  homebrew:
    packages:
      - qt
      - open-mesh
      - pugixml
      - bison
      - flex
      - cmake
      - antlr
    update: True


script:
 - cmake . && make
