name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: checkout submodules
      run: git submodule update --init --recursive
    - name: download dependencies
      run: wget https://www.antlr.org/download/antlr-4.8-complete.jar
    - name: install ubuntu packages
      run: sudo apt-get update && sudo apt-get install -y qt3d5-dev qt3d-*-plugin bison flex uuid-dev
    - name: install vcpkg packages
      run: vcpkg install openmesh pugixml opensubdiv
    - name: configure
      run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$(pwd)/../install -DANTLR_EXECUTABLE=$(pwd)/../antlr-4.8-complete.jar -DCMAKE_PREFIX_PATH=/usr/local/share/vcpkg/installed/x64-linux
    - name: make
      run: make
      working-directory: build
    - name: make install
      run: make install
      working-directory: build
